## Welcome {#welcome}

The aim of this part of the workshop is to introduce phylogenies as potential tools for conservation. We'll first examine what phylogenies are (what do they describe? how do we "read" them?), then we'll check out how to read them into R, and manipulate them as data objects (e.g. how to subset them, plot different parts, join them to useful data etc.)

## Installing relevant packages {#intalling-packages}


The packages used in these exercises are `ape`, `caper`, `geiger` and `picante`. Install them in the usual way e.g. `install.packages("ape")` and load them with `library("ape")`.

```{r, echo=FALSE,message=FALSE}
library("ape")
library("caper")
library("geiger")
library("picante")
```


#### Contents

<ul class="toc">
  <li><a href="Introduction.html">Introduction</a></li>

<li class="dropdown-header">Basics</li>
<li><a href="readingdata.html">Reading data</a></li>
<li><a href="manipulatingtrees.html">Manipulating Trees</a></li>
<li><a href="plottingtrees.html">Plotting Trees</a></li>
<li><a href="phylogeneticsignal.html">Phylogenetic Signal</a></li>


<li class="dropdown-header">Exercises</li>
<li><a href="exercises.html">Exercises</a></li>
<li><a href="signal.html">Signal in Demographic Traits</a></li>

<li class="dropdown-header">More</li>
<li><a href="usefulfunctionsanddata.html">Useful stuff</a></li>

</ul>


## Some useful references

Blomberg, S., Garland, T., & Ives, A. (2003). Testing for phylogenetic signal in comparative data: Behavioral traits are more labile. Evolution, 57(4), 717-745. [Deals with Blomberg's K.]

Cooper, N., & Purvis, A. (2010). Body Size Evolution in Mammals: Complexity in Tempo and Mode. The American Naturalist, 175(6), 727-738. [Testing different models of evolution.]

Felsenstein, J. (1985). Phylogenies and the Comparative Method. The American Naturalist, 125(1), 1-15. The University of Chicago Press.

Freckleton, R. P., Harvey, P., & Pagel, M. (2002). Phylogenetic analysis and comparative data: A test and review of evidence. The American Naturalist, 160(6), 712-726. [pgls models]

Freckleton, R. P. (2009). The seven deadly sins of comparative analysis. Journal Of Evolutionary Biology, 22(7), 1367-1375. [General overview]

Garland, T., Harvey, P., & Ives, A. (1992). Procedures for the Analysis of Comparative Data Using Phylogenetically Independent Contrasts. Systematic Biology, 41(1), 18-32.

Pagel, M. (1999). Inferring the historical patterns of biological evolution. Nature, 401(6756), 877-884. [Deals with lambda, delta, and kappa branch length transformations]

